apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    kubernetes.io/metadata.name: cert-manager
    kustomize.toolkit.fluxcd.io/name: namespaces
    kustomize.toolkit.fluxcd.io/namespace: flux-system
