apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    kubernetes.io/metadata.name: metallb-system
    kustomize.toolkit.fluxcd.io/name: namespaces
    kustomize.toolkit.fluxcd.io/namespace: flux-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    kubernetes.io/metadata.name: ingress-nginx
    kustomize.toolkit.fluxcd.io/name: namespaces
    kustomize.toolkit.fluxcd.io/namespace: flux-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: webapp
  labels:
    kubernetes.io/metadata.name: webapp
    kustomize.toolkit.fluxcd.io/name: namespaces
    kustomize.toolkit.fluxcd.io/namespace: flux-system
