apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 10m0s
  url: https://kubernetes.github.io/ingress-nginx
  timeout: 3m0s
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 1m0s
  chart:
    spec:
      chart: ingress-nginx
      version: 4.7.3
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  valuesFrom:
    - kind: ConfigMap
      name: values
