apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
configMapGenerator:
  - name: values
    namespace: ingress-nginx
    files:
      - values.yaml
configurations:
  - kustomizeconfig.yaml
resources:
  - helm.yaml
