controller:
  watchIngressWithoutClass: true
  extraArgs:
    enable-ssl-passthrough: true
  service:
    enableHttp: true
    enableHttps: true
    # annotations:
    #   external-dns.alpha.kubernetes.io/hostname: marokiki.net.
    loadBalancerIP: "240b:250:9800:4a20:100::1"
    # loadBalancerIP: 192.168.20.231
    ipFamilyPolicy: PreferDualStack
    # ipFamilyPolicy: SingleStack
    ipFamilies:
    # - IPv4
    - IPv6
    ports:
      http: 80
      https: 443
    targetPorts:
      http: http
      https: https
    type: LoadBalancer
